#This script takes feature_matrix_222.csv generated by combining all feature_csvs and corrects a few things before running the WDNN:

feature_mat <- read.csv("feature_matrix_222_03.09.20.csv", stringsAsFactors = FALSE)

#1. The only thing I have noticed so far is for the feature "SNP_CN_4407904_GA_gid_S100F" where I had it as being present in almost all isolates in the input matrix. This is because the feature itself was mislabeled as G-->A whereas the reference allele is actually A so it should be A --> G. I have fixed the input for now (but haven't re-ran the WDNN, although the only effect I anticipate is on the specificity for Streptomycin). Maybe I will find more such issues once I can run isolates on genTB.
#Change "SNP_CN_4407904_FA_gid_S100F" i.e. 90th column

feature_mat[,"V90"] <- 1 - feature_mat[,"V90"] 

#NAs
#NAs reflect presence of feature but inability to calculate alt allele frequnce, so replace with 1
feature_mat[is.na(feature_mat)] <- 1

#Round down to 1 any alt frequencies > 1

feature_mat[feature_mat > 1] <- 1

write.csv(feature_mat, "feature_mat_222_030920_gidNAcorrected.csv", row.names = FALSE)
